name: Terraform Plan, Python Lint, and PyTest

on:
  pull_request:
    paths:
      - 'terraform/**'
      - 'src/**'
      - 'tests/**'
  workflow_dispatch:

jobs:
  changed-files:
    runs-on: ubuntu-latest
    name: Get changed files
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # Use the `changed-files` action to get all the changed files in the PR
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files_yaml: |
            terraform:
              - 'terraform/**'
            src:
              - 'src/**'
            tests:
              - 'tests/**'

  terraform-plan:
    needs: changed-files
    runs-on: ubuntu-latest
    if: steps.changed-files.outputs.terraform_any_changed == 'true'
    steps:
      - name: Set up Terraform 1.11.0
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.0"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run terraform init
        working-directory: terraform
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-1"
      - name: Run terraform plan
        working-directory: terraform
        run: terraform plan -no-color
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-1"

  python-lint:
    needs: changed-files
    runs-on: ubuntu-latest
    if: steps.changed-files.outputs.src_any_changed == 'true' || steps.changed-files.outputs.tests_any_changed == 'true'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Run Ruff
        uses: astral-sh/ruff-action@v3

  pytest:
    needs: [python-lint]
    runs-on: ubuntu-latest
    if: steps.changed-files.outputs.src_any_changed == 'true' || steps.changed-files.outputs.tests_any_changed == 'true'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
      - name: Run PyTest
        working-directory: tests
        run: |
          pytest --maxfail=0 --disable-warnings -q
